### ISSUE TITLE
docker启动就一直卡这里了。。。

### ISSUE THREAD

**Issue by blockchainsecure** [VKSRC/Github-Monitor#1]
[root@localhost Github-Monitor]# docker-compose up -d
Creating network "github-monitor_default" with the default driver
Pulling mysql (mysql:5.7)...
5.7: Pulling from library/mysql
===========
docker启动就一直卡这里了。。。

**Comment by AnYeMoWang** [comment]
@blockchainsecure  这个是正在pull mysql的镜像到本地。如果时间比较久的话，应该是由于网络问题导致的

**Comment by blockchainsecure** [comment]
ERROR: error parsing HTTP 408 response body: invalid character '<' looking for beginning of value: "<html><body><h1>408 Request Time-out</h1>\nYour browser didn't send a complete request in time.\n</body></html>\n\n"

**Comment by AnYeMoWang** [comment]
@blockchainsecure [https://docs.docker.com/engine/reference/commandline/pull/](https://docs.docker.com/engine/reference/commandline/pull/)
