### ISSUE TITLE
搭建环境时出错，无法加载

### ISSUE THREAD

**Issue by chenxs-sx** [VKSRC/Github-Monitor#108]
![image](https://user-images.githubusercontent.com/55311634/113590206-f4081b00-9664-11eb-90c8-203a2281e0d3.png)
报错内容。
有大神能帮助解决下嘛

**Comment by PINGXcpost** [comment]
我也是

**Comment by wdsjxh** [comment]
我也是重新docker装下，报同样的错误

**Comment by chenxs-sx** [comment]
解决不了哇。有解决掉的吗？

**Comment by dhcty** [comment]
> ![image](https://user-images.githubusercontent.com/55311634/113590206-f4081b00-9664-11eb-90c8-203a2281e0d3.png)
> 报错内容。
> 有大神能帮助解决下嘛

pip版本的问题，更新即可，在Dockerfile的`RUN pip3 install -r /requirement.txt`命令之前加入升级pip的命令(之所以要小于21.0是因为最新版本python3.5用不了)：
FROM ubuntu:16.04
MAINTAINER Tuuu Nya<song@secbox.cn>

# install system requirement
RUN sed -i s/archive.ubuntu.com/mirrors.aliyun.com/g /etc/apt/sources.list
RUN sed -i s/security.ubuntu.com/mirrors.aliyun.com/g /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y python3 python3-dev python3-pip nginx supervisor libmysqlclient-dev redis-server libssl-dev libffi-dev && \
    rm -rf /var/lib/apt/lists/*

# setup all the configfiles
RUN echo "daemon off;" >> /etc/nginx/nginx.conf
RUN rm -rf /etc/nginx/sites-enabled/default
RUN sed -i '/include \/etc\/nginx\/sites-enabled\//a\\tinclude /home/docker/Github-Monitor/docker/nginx-app.conf;' /etc/nginx/nginx.conf
RUN sed -i 's/\/etc\/supervisor\/conf.d\/\*.conf/\/home\/docker\/Github-Monitor\/docker\/supervisor-app.conf/g' /etc/supervisor/supervisord.conf

# install requirement
**RUN python3 -m pip install --upgrade "pip<21.0"**
COPY server/requirements.pip /requirement.txt
RUN pip3 install -r /requirement.txt

# volumne
VOLUME ["/var/lib/redis"]
VOLUME ["/home/docker/Github-Monitor/"]

WORKDIR /home/docker/Github-Monitor/

ENV LANG C.UTF-8

EXPOSE 80

CMD ["/bin/bash", "/home/docker/Github-Monitor/docker/run.sh"]

**Comment by TuuuNya** [comment]
@dhcty  正解，完整的可以参考 #115

**Comment by wdsjxh** [comment]
感谢
