### ISSUE TITLE
一直卡在这个界面，登不上去……

### ISSUE THREAD

**Issue by 0rzNuII** [VKSRC/Github-Monitor#122]
![image](https://user-images.githubusercontent.com/40875899/129851665-5b8a8493-ebf9-4b3e-8868-bc45eb85d9f6.png)

**Comment by GigiJiang** [comment]
同问

**Comment by TuuuNya** [comment]
打开F12，看看网络请求有没有报错，如果有，贴出来。

**Comment by 0rzNuII** [comment]
> 打开F12，看看网络请求有没有报错，如果有，贴出来。

![image](https://user-images.githubusercontent.com/40875899/131843232-42681207-4b5f-4fcc-99a7-9ee82395eef9.png)

**Comment by 0rzNuII** [comment]
> 打开F12，看看网络请求有没有报错，如果有，贴出来。

![image](https://user-images.githubusercontent.com/40875899/131843898-21e4c097-90e9-4fd5-afc1-69b3197d9f09.png)

**Comment by 0rzNuII** [comment]
> 同问

我知道为什么了，不要改.env的mysql连接信息，我他妈服了。。。
好，此贴完结！
