### ISSUE TITLE
/api/user等 返回400 求原因

### ISSUE THREAD

**Issue by bonjour-py** [VKSRC/Github-Monitor#127]
![image](https://user-images.githubusercontent.com/33248848/158305592-fd7cbdf2-8a0d-44d0-93b6-6dcb2721f5b2.png)
![image](https://user-images.githubusercontent.com/33248848/158305448-a517219c-c6a9-43c7-bd9b-5ff1f52ceb7c.png)
![image](https://user-images.githubusercontent.com/33248848/158305870-99a95964-f412-49f8-acfa-7bf6e1ba6832.png)

**Comment by TuuuNya** [comment]
有没有可能，是没改allow_hosts

**Comment by bonjour-py** [comment]
求问 allow_hosts 中的* 是干什么的

**Comment by bonjour-py** [comment]
感谢
