### ISSUE TITLE
docker部署，访问出现空白界面，浏览器控制台提示错误

### ISSUE THREAD

**Issue by haorenx** [VKSRC/Github-Monitor#14]
![image](https://user-images.githubusercontent.com/8851007/50390159-8a52f400-076e-11e9-92d5-c1d4c8927d10.png)

看图

**Comment by TuuuNya** [comment]
@haorenx  应该是后端没跑起来吧，重新运行试试。

**Comment by haorenx** [comment]
@TuuuNya docker-composer up -d   显示Starting github-monitor_mysql_1_2b83f1c4c0db ... done 
Starting github-monitor_web_1_5e2dc2b99ee2   ... done。这样不行？

**Comment by TuuuNya** [comment]
@haorenx  看了一下，你访问的地址不对，正确的url是`/list` 而不是`/github/list`，可能是浏览器缓存的原因， 你清理一下浏览器缓存，强制刷新试试。

**Comment by haorenx** [comment]
从任务管理界面过去的url确实是github/list
![image](https://user-images.githubusercontent.com/8851007/50390625-524eaf80-0774-11e9-89c4-55d81f89eced.png)，这是个bug
