### ISSUE TITLE
设置allowed_host为0.0.0.0或者远程主机ip都不能远程访问Github-Monitor

### ISSUE THREAD

**Issue by wooyunvip** [VKSRC/Github-Monitor#17]
远程访问Github-Monitor该如何配置？

**Comment by AnYeMoWang** [comment]
@wooyunvip 你在浏览器里访问的ip或者域名是什么，allowed_hosts就写什么。

**Comment by wooyunvip** [comment]
> @wooyunvip 你在浏览器里访问的ip或者域名是什么，allowed_hosts就写什么。

有点歧意，应该allowed_hosts是Github-Monitor服务的外网IP或者内网IP
