### ISSUE TITLE
centos 7 下得关闭 selinux

### ISSUE THREAD

**Issue by M2shad0w** [VKSRC/Github-Monitor#18]
![2018-12-26 12-19-14](https://user-images.githubusercontent.com/3387446/50432385-59a8c100-090c-11e9-8581-c4258c0767cb.png)

**Comment by TuuuNya** [comment]
@M2shad0w 

Centos7安全Selinux禁止了一些安全权限，导致mysql和mariadb在进行挂载/var/lib/mysql的时候会报权限错误。

搜索引擎上有解决方案：
https://www.cnblogs.com/performancetest/p/5719420.html
