### ISSUE TITLE
 本地安装时 npm install && npm run start 各种报错

### ISSUE THREAD

**Issue by 219liangyi** [VKSRC/Github-Monitor#2]
麻烦提供一下本地安装的node,npm版本号。猜测是版本号导致的问题
1258 error TypeError: Cannot read property 'latest' of undefined
1258 error     at next (/usr/lib/node_modules/npm/lib/cache.js:687:35)
1258 error     at /usr/lib/node_modules/npm/lib/cache.js:675:5
1258 error     at saved (/usr/lib/node_modules/npm-registry-client/lib/get.js:148:7)
1258 error     at /usr/lib/node_modules/graceful-fs/polyfills.js:133:7
1258 error     at Object.oncomplete (fs.js:108:15)
1259 error If you need help, you may report this log at:
1259 error     <http://github.com/isaacs/npm/issues>
1259 error or email it to:
1259 error     <npm-@googlegroups.com>
1260 error System Linux 2.6.32-573.22.1.el6.x86_64
1261 error command "node" "/usr/bin/npm" "install"
1262 error cwd /opt/web/Github-Monitor/client
1263 error node -v v0.10.48
1264 error npm -v 1.3.6
1265 error type non_object_property_load
1266 verbose exit [ 1, true ]

**Comment by TuuuNya** [comment]
使用高版本的node和npm应该是没问题的。

**Comment by hitao123** [comment]
npm 安装报错

```
4696 verbose stack ZlibError: zlib: unexpected end of file
4696 verbose stack     at Zlib.(anonymous function).onerror (/usr/local/lib/node_modules/npm/node_modules/minizlib/index.js:131:21)
4696 verbose stack     at Unzip.write (/usr/local/lib/node_modules/npm/node_modules/minizlib/index.js:255:31)
4696 verbose stack     at Unzip.flush (/usr/local/lib/node_modules/npm/node_modules/minizlib/index.js:222:10)
4696 verbose stack     at Unzip.end (/usr/local/lib/node_modules/npm/node_modules/minizlib/index.js:229:10)
4696 verbose stack     at Object.end (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:415:21)
4696 verbose stack     at PassThrough.onend (_stream_readable.js:631:10)
4696 verbose stack     at Object.onceWrapper (events.js:273:13)
4696 verbose stack     at PassThrough.emit (events.js:187:15)
4696 verbose stack     at endReadableNT (_stream_readable.js:1086:12)
4696 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by hitao123** [comment]
@219liangyi  node 0.10.48 版本太低， 现在都到 10.X，我这个版本都是挺高的，不知道安装依赖还是有问题

**Comment by TuuuNya** [comment]
@hitao123  我本地使用的版本，install和build都是没有问题的。

```
➜ npm -v
5.3.0

~
➜ node -v
v8.4.0
```

另外，我们的服务器在部署的时候，全用的是最新版，也是没有问题的。
