### ISSUE TITLE
邮箱告警未测试成功

### ISSUE THREAD

**Issue by a9681417** [VKSRC/Github-Monitor#24]
邮箱告警没测试成功，是不是163邮箱的不好用呀，可以推荐个邮箱吗？我已经使用授权码登陆了，还是没有收到邮件。可以详细说一下 邮箱告警的设置过程吗？跪求。

**Comment by AnYeMoWang** [comment]
在.env文件里配置就可以了。
`
# Email Settings
# If you do not fill it in, it is None/False
EMAIL_HOST="smtp.163.com"  # smtp host
EMAIL_PORT="25"  # smtp port
FROM_EMAIL="xxx@163.com"  # 发件人
EMAIL_HOST_USER="xxx@163.com"  # email user, 如为匿名发送，将值设为空字符即可
EMAIL_HOST_PASSWORD="xxxx"  # email password, 如为匿名发送，将值设为空字符即可
EMAIL_USE_TLS="False"  # 与SMTP服务器通信时是否使用TLS（安全）连接, 可选True/False
EMAIL_USE_SSL="False"  # 与SMTP服务器通信时是否使用SSL（安全）连接, 可选True/False
`

`EMAIL_HOST_PASSWORD` 中填的是邮箱授权码。
