### ISSUE TITLE
定期执行|手动启动

### ISSUE THREAD

**Issue by bloodzer0** [VKSRC/Github-Monitor#26]
1.目前貌似没有看到自定义多长时间执行一次任务；
2.手动执行，我之前添加的关键字，我现在想手动执行一次功能是否考虑；

**Comment by TuuuNya** [comment]
![image](https://user-images.githubusercontent.com/14834081/51160334-795a5600-18c8-11e9-9e9c-38ff6e1e0a41.png)

默认会按照设置的间隔自动执行任务，添加以后就会自动执行。
