### ISSUE TITLE
源码部署访问一次就页面空白了

### ISSUE THREAD

**Issue by rockmelodies** [VKSRC/Github-Monitor#28]
好奇怪

**Comment by rockmelodies** [comment]
![image](https://user-images.githubusercontent.com/24653177/51231654-34552300-199f-11e9-86b6-7b73b526d881.png)

**Comment by TuuuNya** [comment]
@rockmelodies  查看一下网络面板，后端请求是否成功。  

另外pull一下最新代码，目测是ALLOWED_HOST没配置。

**Comment by rockmelodies** [comment]
![image](https://user-images.githubusercontent.com/24653177/51231878-fad0e780-199f-11e9-888e-941155b8222b.png)

**Comment by rockmelodies** [comment]
这样配可以吗

**Comment by rockmelodies** [comment]
![image](https://user-images.githubusercontent.com/24653177/51231964-4aafae80-19a0-11e9-80da-c141abfbd479.png)

**Comment by AnYeMoWang** [comment]
> 这样配可以吗

@rockmelodies 这么配置是没问题的。* 的意思是允许所有host请求, 仅在DBEUG为True的时候生效。

**Comment by rockmelodies** [comment]
好奇怪
