### ISSUE TITLE
现在访问一直停留在这个页面

### ISSUE THREAD

**Issue by rockmelodies** [VKSRC/Github-Monitor#29]
![image](https://user-images.githubusercontent.com/24653177/51234776-ad0cad00-19a8-11e9-9a76-8469ac5a26bf.png)

**Comment by AnYeMoWang** [comment]
@rockmelodies  进群我加你聊吧。你的部署方式看起来存在问题
![wechatimg179](https://user-images.githubusercontent.com/10385628/51235260-04f7e380-19aa-11e9-8edb-0fdce731570c.jpeg)
