### ISSUE TITLE
Option To scan a Particular Organization or User

### ISSUE THREAD

**Issue by d3ad1Yb0073r** [VKSRC/Github-Monitor#31]
Hi
any way to scan a particular organization or a specific user ?

**Comment by AnYeMoWang** [comment]
@d3ad1Yb0073r You can add keyword such like `aaa user:USERNAME `、`aaa org:ORGNAME `.  Here is the github searching api documention: [search-within-a-users-or-organizations-repositories](https://help.github.com/articles/searching-code/#search-within-a-users-or-organizations-repositories) .
