### ISSUE TITLE
页面返回500

### ISSUE THREAD

**Issue by Hipsdontlie** [VKSRC/Github-Monitor#36]
![image](https://user-images.githubusercontent.com/30896055/53890907-1ed9ac80-4064-11e9-98d8-731782d70352.png)

**Comment by TuuuNya** [comment]
@zmyudehao  请提供 http 500报错的详细内容。

**Comment by zmyudehao** [comment]
我是docker直接部署的，启动也没有报错，但是访问就是500
![image](https://user-images.githubusercontent.com/30896055/53930869-f4243e00-40cd-11e9-9872-a987378259d2.png)

**Comment by TuuuNya** [comment]
@zmyudehao  请提供后端接口的报错内容

查看方式：http://www.cnblogs.com/awzf/p/9890725.html

**Comment by zmyudehao** [comment]
![image](https://user-images.githubusercontent.com/30896055/53935556-b5987e80-40e1-11e9-9dc1-d482e04038da.png)

**Comment by TuuuNya** [comment]
@zmyudehao 把response里面的内容发出来

![image](https://user-images.githubusercontent.com/14834081/53935615-0019fb00-40e2-11e9-8fbc-c65b4ceabc99.png)

**Comment by zmyudehao** [comment]
![image](https://user-images.githubusercontent.com/30896055/53935689-44a59680-40e2-11e9-8ae1-05163755fdb8.png)

**Comment by TuuuNya** [comment]
@zmyudehao  麻烦你把.env里面的debug改成True，然后`docker-compose restart` 一下，再看HTTP的报错信息。

**Comment by Hipsdontlie** [comment]
![image](https://user-images.githubusercontent.com/30896055/53935938-1ffdee80-40e3-11e9-8df7-ed9b14251db6.png)
默认的不就是true么。。

**Comment by TuuuNya** [comment]
加我微信吧， StrikerSb  看看你这什么情况。

**Comment by hack2012** [comment]
我也出现了同样的问题，docker环境变windows下面的，然后报错的url为:8001/api/user/:1 Failed to load resource: the server responded with a status of 502 (Bad Gateway)

**Comment by AnYeMoWang** [comment]
@hack2012 windows下git clone好像会把所有文件的换行符都替换成 
  你手工把.env文件里的换行符替换成 
 后再重启docker服务试一下
