### ISSUE TITLE
web容器启动失败

### ISSUE THREAD

**Issue by alexanderhawl** [VKSRC/Github-Monitor#37]
使用docker方法安装，docker和docker-compose已装好。配置文件没有修改。使用docker-compose启动时只有mysql容器启动成功。启动日志：
Attaching to githubmonitor_web_1, githubmonitor_mysql_1
web_1    | /bin/bash: /home/docker/Github-Monitor/docker/run.sh: Permission denied
mysql_1  | chown: cannot read directory '/var/lib/mysql/': Permission denied
mysql_1  | chown: cannot read directory '/var/lib/mysql/': Permission denied
mysql_1  | chown: cannot read directory '/var/lib/mysql/': Permission denied
mysql_1  | chown: cannot read directory '/var/lib/mysql/': Permission denied
mysql_1  | chown: cannot read directory '/var/lib/mysql/': Permission denied
mysql_1  | chown: cannot read directory '/var/lib/mysql/': Permission denied
mysql_1  | chown: cannot read directory '/var/lib/mysql/': Permission denied
mysql_1  | chown: cannot read directory '/var/lib/mysql/': Permission denied
mysql_1  | chown: cannot read directory '/var/lib/mysql/': Permission denied
mysql_1  | chown: cannot read directory '/var/lib/mysql/': Permission denied
mysql_1  | chown: cannot read directory '/var/lib/mysql/': Permission denied

**Comment by TuuuNya** [comment]
https://www.jianshu.com/p/bccda875e7a5
