### ISSUE TITLE
在github中使用双引号能进行精确搜索，但这里面不可以

### ISSUE THREAD

**Issue by alexanderhawl** [VKSRC/Github-Monitor#39]
例如:我在github中搜索"baidu.com",返回的结果中都含有baidu.com,但这里面使用关键词搜索”baidu.com",返回的结果有些只包括com

**Comment by AnYeMoWang** [comment]
你可以看一下这个链接: [considerations-for-code-search](https://help.github.com/en/articles/searching-code#considerations-for-code-search)

这里有写到:
> You can't use the following wildcard characters as part of your search query: . , : ; / \ ` ' " = * ! ? # $ & + ^ | ~ < > ( ) { } [ ]. The search will simply ignore these symbols. 

即这些特殊字符都无法在搜索中生效，会被直接忽略掉。

你在github中直接搜索也是无法匹配这些特殊字符的，你可以搜索 "baidu.alibaba" 试一下

**Comment by TuuuNya** [comment]
@alexanderhawl  现在最新版本的Github Monitor已经支持精确搜索啦！ #59
