### ISSUE TITLE
如何修改爬取类型

### ISSUE THREAD

**Issue by lupus721** [VKSRC/Github-Monitor#40]
如何修改爬取类型，比如说 我现在想完全不关注ipynb这个类型的结果，如何设置呢。在使用说明里面没有看到设置。

还有 在哪里有结果搜索的功能设置，比如我现在想只看.conf类的结果

什么 时候有批量忽略的功能啊，比如一版的结果都不是我要的，直接选择批量忽略

**Comment by AnYeMoWang** [comment]
@lupus721 
* 我们的关键词输入是支持github搜索语法的。[search-by-file-extension](https://help.github.com/en/articles/searching-code#search-by-file-extension) 如果你只想关注conf类型的文件，可以在关键词后面加上 `extension: conf`, 比如 `vipkid extension:conf`.
* 我们目前有忽略仓库的功能，可以批量忽略该仓库下的所有发现的内容。我认为这个功能已经可以满足实际使用的需求了。
