### ISSUE TITLE
前端使用https，登录时报错

### ISSUE THREAD

**Issue by alexanderhawl** [VKSRC/Github-Monitor#44]
![image](https://user-images.githubusercontent.com/22365038/55301189-d4362f00-546d-11e9-86c7-97ac7efded4c.png)
![image](https://user-images.githubusercontent.com/22365038/55301219-09db1800-546e-11e9-94bb-d8ae9857b4f9.png)
采用源代码部署的。使用了slb做https的转发。用http能够成功登录。但是https转发后就报错。

**Comment by AnYeMoWang** [comment]
@alexanderhawl 自己google一下 "the content must served over https"

**Comment by hack2012** [comment]
我也遇到了这个问题。。正在想办法解决。

**Comment by AnYeMoWang** [comment]
@hack2012 该问题已修复 #56  你可以更新一下代码
