### ISSUE TITLE
升级之后监控没有反应

### ISSUE THREAD

**Issue by rockmelodies** [VKSRC/Github-Monitor#45]
页面可以正常访问，为啥爬不到数据

**Comment by rockmelodies** [comment]
![image](https://user-images.githubusercontent.com/24653177/56087453-56771800-5e9e-11e9-8857-e8bda23a9512.png)

**Comment by AnYeMoWang** [comment]
@rockmelodies 找到原因了吗？你是docker部署的还是手工部署的
