### ISSUE TITLE
docker 成功安装后访问web界面一闪而过

### ISSUE THREAD

**Issue by pt001** [VKSRC/Github-Monitor#5]
docker 成功安装后访问http://127.0.0.1:8001 web界面一闪而过，直接跳转到http://127.0.0.1:8001/list页面，页面空白。右键源代码如下：

  | <!DOCTYPE html><html lang="en"><head><link rel="stylesheet" href="/umi.css"><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Github Monitor</title><link rel="icon" href="/favicon.ico" type="image/x-icon"><script src="https://gw.alipayobjects.com/os/antv/pkg/_antv.data-set-0.9.6/dist/data-set.min.js"></script><script>window.routerBase = "/";</script></head><body>
-- | --
  | <link rel="stylesheet/less" type="text/css" href="/color.less" />
  | <script>
  | window.less = {
  | async: false,
  | env: 'production'
  | };
  | </script>
  | <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/less.js/2.7.2/less.min.js"></script>
  | <div id="root"></div><script src="/umi.js"></script><script>(function(){
  | if (!location.port) {
  | (function (i, s, o, g, r, a, m) {
  | i['GoogleAnalyticsObject'] = r;
  | i[r] = i[r] \|\| function () {
  | (i[r].q = i[r].q \|\| []).push(arguments)
  | }, i[r].l = 1 * new Date();
  | a = s.createElement(o),
  | m = s.getElementsByTagName(o)[0];
  | a.async = 1;
  | a.src = g;
  | m.parentNode.insertBefore(a, m)
  | })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
  | ga('create', 'UA-72788897-6', 'auto');
  | ga('send', 'pageview');
  | }
  | })();</script></body></html>

**Comment by shellfeel** [comment]
咋解决的 我是同样的问题

**Comment by TuuuNya** [comment]
> 咋解决的 我是同样的问题

@shellfeel  麻烦把console和network面板截图看看

**Comment by shellfeel** [comment]
![image](https://user-images.githubusercontent.com/18633010/50259858-dafde080-0440-11e9-85b7-24c7def07b11.png)
![image](https://user-images.githubusercontent.com/18633010/50259882-f537be80-0440-11e9-8a31-e84a2d829ec4.png)
松哥帮忙看下

**Comment by shellfeel** [comment]
原来如此，我以为这做的访问控制呢~ haha， thx
