### ISSUE TITLE
服务启动完成页面无法访问

### ISSUE THREAD

**Issue by shengtaowang** [VKSRC/Github-Monitor#51]
您好。我是通过docker方式部署的，部署完成没有报错，8001端口也起来了，但是无法通过页面访问。不知道是何原因？求解。

- [root@localhost Github-Monitor]# docker-compose restart
- Restarting github-monitor_web_1 … done
- Restarting github-monitor_mysql_1 … done
- [root@localhost Github-Monitor]#
- [root@localhost Github-Monitor]# netstat -an|grep 8001
- tcp6 0 0 :::8001 :::* LISTEN
- [root@localhost Github-Monitor]#
- [root@localhost Github-Monitor]# curl http://127.0.0.1:8001
- curl: (56) Recv failure: Connection reset by peer
- [root@localhost Github-Monitor]#
- [root@localhost Github-Monitor]# curl http://localhost:8001
- curl: (56) Recv failure: Connection reset by peer
- [root@localhost Github-Monitor]#

**Comment by TuuuNya** [comment]
注意: 第一次启动由于mysql容器启动时间较久，可能会用30s左右的时间，页面才可以正常访问

**Comment by shengtaowang** [comment]
貌似不是30秒的问题，从昨天部署到现在还是无法访问，IP白名单也加进去了。

**Comment by TuuuNya** [comment]
`docker-compose logs` 看看。

**Comment by shengtaowang** [comment]
[root@localhost Github-Monitor]# docker-compose logs -t
Attaching to github-monitor_web_1, github-monitor_mysql_1
web_1    | 2019-05-28T02:30:56.296887000Z wait-for-it.sh: waiting for mysql:3306 without a timeout
mysql_1  | 2019-05-28T02:30:10.048183000Z chown: changing ownership of '/var/lib/mysql/': Permission denied
mysql_1  | 2019-05-28T02:30:11.046431000Z chown: changing ownership of '/var/lib/mysql/': Permission denied
mysql_1  | 2019-05-28T02:30:12.369130000Z chown: changing ownership of '/var/lib/mysql/': Permission denied
mysql_1  | 2019-05-28T02:30:13.645140000Z chown: changing ownership of '/var/lib/mysql/': Permission denied
mysql_1  | 2019-05-28T02:30:15.272269000Z chown: changing ownership of '/var/lib/mysql/': Permission denied
mysql_1  | 2019-05-28T02:30:17.845484000Z chown: changing ownership of '/var/lib/mysql/': Permission denied
mysql_1  | 2019-05-28T02:30:21.920930000Z chown: changing ownership of '/var/lib/mysql/': Permission denied
mysql_1  | 2019-05-28T02:30:28.848925000Z chown: changing ownership of '/var/lib/mysql/': Permission denied
mysql_1  | 2019-05-28T02:30:42.262952000Z chown: changing ownership of '/var/lib/mysql/': Permission denied
mysql_1  | 2019-05-28T02:31:08.631279000Z chown: changing ownership of '/var/lib/mysql/': Permission denied
我是用systemctl start docker命令来启动docker的，有人说上面的错误是Centos7安全Selinux禁止了一些安全权限，导致mysql在进行挂载/var/lib/mysql的时候失败，我尝试禁用了Selinux，重启系统后依然报错。

**Comment by shengtaowang** [comment]
问题解决了，感谢。刚才是禁用SELINUX没有生效导致的。

**Comment by lyfzaiyi** [comment]
我的问题和那个兄弟的类似，部署完docker后，不能登录页面，我用的ubuntu16.04，

**Comment by shengtaowang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
