### ISSUE TITLE
docker-compose up -d启动失败

### ISSUE THREAD

**Issue by ChrisAaron** [VKSRC/Github-Monitor#52]
W: The repository 'http://mirrors.aliyun.com/ubuntu xenial Release' does not have a Release file.
W: The repository 'http://mirrors.aliyun.com/ubuntu xenial-updates Release' does not have a Release file.
W: The repository 'http://mirrors.aliyun.com/ubuntu xenial-backports Release' does not have a Release file.
W: The repository 'http://mirrors.aliyun.com/ubuntu xenial-security Release' does not have a Release file.
E: Failed to fetch http://mirrors.aliyun.com/ubuntu/dists/xenial/main/binary-amd64/Packages  Connection failed [IP: 42.81.12.220 80]
E: Failed to fetch http://mirrors.aliyun.com/ubuntu/dists/xenial-updates/main/binary-amd64/Packages  Connection failed [IP: 124.238.244.234 80]
E: Failed to fetch http://mirrors.aliyun.com/ubuntu/dists/xenial-backports/main/binary-amd64/Packages  Connection failed [IP: 42.81.4.215 80]
E: Failed to fetch http://mirrors.aliyun.com/ubuntu/dists/xenial-security/main/binary-amd64/Packages  Connection failed [IP: 42.81.12.219 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
ERROR: Service 'web' failed to build: The command '/bin/sh -c apt-get update' returned a non-zero code: 100

**Comment by TuuuNya** [comment]
重复issue #11

**Comment by ChrisAaron** [comment]
关键 我是国内服务器。另外dockerfile里面创建镜像是基于Ubuntu的，而我的系统是centos7。

**Comment by TuuuNya** [comment]
@ChrisAaron   Docker创建的镜像和你服务器的系统没有关系， 这个错误是网络问题，请多尝试一下吧。

**Comment by ChrisAaron** [comment]
好的 谢谢

**Comment by ChrisAaron** [comment]
是不是应该dockerfile中镜像源地址改成https的方式？
