### ISSUE TITLE
邮件无法发送

### ISSUE THREAD

**Issue by testtestu** [VKSRC/Github-Monitor#54]
env文件里已经配置好了，邮件服务器是开启TLS的，smtp端口465，tls和ssl都设为true，任务里已经填了收件人，还是没收到邮件，看邮件服务器的日志里面没有连接日志，就是说根本没有发起过邮件发送连接
请问如何排查，thx

**Comment by testtestu** [comment]
btw我是docker部署的

**Comment by TuuuNya** [comment]
邮件服务器里面没有连接日志，没有发起过邮件，那很大可能是你的关键词压根就没搜索到泄露项，所以就不会邮件提醒了吧？  你把你关键词在github上搜索试试。

**Comment by testtestu** [comment]
有的，查询界面都有内容

**Comment by TuuuNya** [comment]
那必定是配置问题，建议使用163邮箱试试，要是163邮箱可以，那就是你自己邮箱有问题了。

**Comment by testtestu** [comment]
行吧我试试

**Comment by wangyan0821** [comment]
> 行吧我试试

请问无法发送邮件的问题有什么办法解决吗，我也碰到一样的问题
