### ISSUE TITLE
支持MAC平台吗？

### ISSUE THREAD

**Issue by cyjaysun** [VKSRC/Github-Monitor#58]
npm start时报错 :
Starting Umi UI using umi@2.10.5...
🧨  Ready on http://localhost:3000/
✖  error     [hardSource] is no longer valid. Please remove it from the configuration file.

Warning: umi-plugin-polyfills has been deprecated.
use config.targets instead.

Building dll...

✖ Webpack
  Compiled with some errors in 12.31s

 ERROR  Failed to compile with 1 errors                                                                                                                           下午2:46:30

This dependency was not found:

* ws in ./node_modules/puppeteer/lib/WebSocketTransport.js

To install it, you can run: npm install --save ws

 ERROR CODE  ERR_WEBPACK_DLL_MODULE_NOT_FOUND

 DETAILS 
===
npm install --save ws尝试过了也不行

**Comment by TuuuNya** [comment]
支持Mac的，GithubMonitor就是在Mac平台下开发的。

首先建议使用 #2 提供的node及npm版本。

如果还无法解决的话，建议按照提示在配置中把hardSource改成false或删掉该配置。

**Comment by cyjaysun** [comment]
> 支持Mac的，GithubMonitor就是在Mac平台下开发的。
> 
> 首先建议使用 #2 提供的node及npm版本。
> 
> 如果还无法解决的话，建议按照提示在配置中把hardSource改成false或删掉该配置。
====
npm -v
5.3.0
node -v
v8.4.0
npm和node版本跟你说的一致，重新试了下还是一样的报错。
配置中也没找到hardSource相关的。
====
Starting Umi UI using umi@2.10.5...
🧨  Ready on http://localhost:3000/
✖  error     [hardSource] is no longer valid. Please remove it from the configuration file.

Warning: umi-plugin-polyfills has been deprecated.
use config.targets instead.


Building dll...

✖ Webpack
  Compiled with some errors in 28.79s

 ERROR  Failed to compile with 1 errors                                                                                                                              16:36:10

This dependency was not found:

* ws in ./node_modules/puppeteer/lib/WebSocketTransport.js

To install it, you can run: npm install --save ws

 ERROR CODE  ERR_WEBPACK_DLL_MODULE_NOT_FOUND

 DETAILS 

## 错误原因

构建 dll 文件时出错了，由于 dependencies 下的依赖会全部被打到 dll 里，所以报错可能有以下原因：

    1. dependencies 里的某些依赖没有 main 文件
    2. 应该放在 devDependencies 里的 node 相关的依赖却写在了 dependencies

## 解决方案

让不该打到 dll 的不被打到 dll 里，有几个解决方案：

    1. 把 node 相关依赖放到 devDependencies 里
    2. 把出错的依赖配置到 dll 的 exclude 里

比如：

    dll: {
      exclude: ['foo']
    }


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@2.0.0 start: `cross-env APP_TYPE=site umi dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ant-design-pro@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

===崩溃～～求指教，感谢🙏

**Comment by TuuuNya** [comment]
删了node_modules目录重新`npm install` 试试。

这种前端工程的问题，建议自己想办法解决。
