### ISSUE TITLE
github-monitor不支持github高级搜索语法吗?

### ISSUE THREAD

**Issue by ba1ma0** [VKSRC/Github-Monitor#60]
设置高级搜索语法之后一直没有结果
![截屏2019-11-1012 39 09](https://user-images.githubusercontent.com/32502627/68538925-1f76cf80-03b7-11ea-8431-5e99c6dd77d2.png)

**Comment by AnYeMoWang** [comment]
@ba1ma0 是支持的哈。你可以把任务截图详细截一下
