### ISSUE TITLE
关闭或者重启容器的时候是否会抹除数据

### ISSUE THREAD

**Issue by binghuixu** [VKSRC/Github-Monitor#63]
使用docker部署的时候，是会构建一个mysql数据库容器的，这个mysql数据库是只用来存放管理员账号密码的数据吗？是否还有保存其他数据的用途？
另外，redis数据库是内建在Github-Monitor容器里吗？redis保存的时什么数据，关闭或者重启容器的时候是否会抹除数据。

总的来说就是，使用docker部署的话，关闭或者重启容器的时候是否会抹除数据，例如加白名单的数据

**Comment by TuuuNya** [comment]
关闭容器或者重启容器不会抹除数据，容器中需要持久化存储的数据都在本项目的`docker/data`目录下。

mysql是用来存放爬到的数据、白名单数据以及管理员账号密码；
redis主要用于github token的管理，redis自己本身会自动保存数据，具体多久保存查阅redis官方文档吧。

**Comment by binghuixu** [comment]
好的，非常感谢！
