### ISSUE TITLE
可以支持多关键词匹配吗

### ISSUE THREAD

**Issue by binghuixu** [VKSRC/Github-Monitor#66]
例如达到以下这种效果:
![image](https://user-images.githubusercontent.com/22317747/70878026-bfe59280-1ffa-11ea-9912-e07d9866b3e8.png)

我配置多个关键词的时候，貌似爬取的时候是只能一个一个关键词匹配，例如以下这样：
![image](https://user-images.githubusercontent.com/22317747/70878331-025b9f00-1ffc-11ea-828e-e603699df882.png)

![image](https://user-images.githubusercontent.com/22317747/70878370-3040e380-1ffc-11ea-8d51-fed7aca7c6d5.png)

**Comment by binghuixu** [comment]
是我配置的方式有问题，还是系统的机制？感谢解答

**Comment by AnYeMoWang** [comment]
@binghuixu 一行是一个关键词。你需要写成 `baidu.com password` 不要换行。
