### ISSUE TITLE
python3 manage.py migrate gbk报错

### ISSUE THREAD

**Issue by lalada-8** [VKSRC/Github-Monitor#72]
源码安装，redis、mysql、前端代码都装好了，依赖装好了，但是python3 manage.py migrate报gbk错
python3.6
![b](https://user-images.githubusercontent.com/65018586/81797137-f63f2380-9540-11ea-9482-c2c39f41ba8d.jpg)

![Snipaste_2020-05-13_17-35-50](https://user-images.githubusercontent.com/65018586/81797193-08b95d00-9541-11ea-8fec-b256f0d83f1a.jpg)

**Comment by Siegelcpp** [comment]
我在Windows上搭建，也遇到了相同的问题，原因不明，建议debian搭建

**Comment by TuuuNya** [comment]
未充分在Windows下测试Github-Monitor，建议在linux下搭建。
