### ISSUE TITLE
邮件发送不成功

### ISSUE THREAD

**Issue by websafe2018** [VKSRC/Github-Monitor#8]
邮件发送是在检测完毕发送吗？ 没有收到邮件，请问邮件这一块的日志在哪里看？ 
我想知道为什么没有成功。

**Comment by AnYeMoWang** [comment]
@websafe2018 你在.env文件里里Email部分的配置是正确的吗？还有就是添加任务的时候需要填写收件人的地址

**Comment by websafe2018** [comment]
正确的哦，已经添加过收件人地址。

**Comment by TuuuNya** [comment]
是否启用了邮件的TLS/SSL加密? 如果开启了可以参考 #9

**Comment by lishion** [comment]
我也遇到了这个问题。看了源代码有个疑问，EMAIL_HOST_PASSWORD 这个字段并未在任何地方使用。如果是这样的话，邮件是如何发送的？

**Comment by AnYeMoWang** [comment]
@lishion 邮件发送使用的是django自带的emailBackend。是在 [settings.py](https://github.com/VKSRC/Github-Monitor/blob/master/server/github_monitor/settings.py) 里配置的
