### ISSUE TITLE
无法发送邮件告警

### ISSUE THREAD

**Issue by lsq-connect** [VKSRC/Github-Monitor#80]
我想使用163邮箱来发送邮件，但是配置相关文档后依旧无法正常发送邮件

**Comment by AnYeMoWang** [comment]
@lsq-connect 配置贴一下吧。密码打码即可

**Comment by lsq-connect** [comment]
刚刚配置好了，发现原参数代码中缺少“DEFAULT_FROM_EMAIL = EMAIL_HOST_USER”，不过配置好邮件告警之后，爬虫就会变得巨慢

**Comment by xjdhu** [comment]
> 
> 
> 刚刚配置好了，发现原参数代码中缺少“DEFAULT_FROM_EMAIL = EMAIL_HOST_USER”，不过配置好邮件告警之后，爬虫就会变得巨慢

请问是自己在.env加下面一段参数吗
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_HOST_USER = "xxx@163.com"

我通过docker部署一直发不了邮件
