### ISSUE TITLE
想了解一个问题，cookie是永久有效的吗？

### ISSUE THREAD

**Issue by gdbingo** [VKSRC/Github-Monitor#85]
如题，部署完之后发现，貌似web控制台的cookie是永久有效的，在浏览器登录了一次之后，隔了一个月之后登录不需用账密验证，直接访问控制台地址就可以访问

**Comment by AnYeMoWang** [comment]
@gdbingo 前后端是通过token认证的、目前token没有配置有效期，是永久生效的
