### ISSUE TITLE
请问现在Github-Monitor支持搜索repo里面issues里面的描述吗？

### ISSUE THREAD

**Issue by daxin09pp** [VKSRC/Github-Monitor#87]
请问现在Github-Monitor支持搜索repo里面issues里面的描述吗？

**Comment by AnYeMoWang** [comment]
@daxin09pp 目前只支持了code的搜索 issue和pr搜索的话github是有相应[api接口](https://developer.github.com/v3/search/#search-issues-and-pull-requests)的。 欢迎来提PR呀
