### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by lupus721** [VKSRC/Github-Monitor#9]
1 如果邮件想启用ssl
```
  EMAIL_USE_TLS=
  EMAIL_USE_SSL=

```
这两个参数怎么设置
2 token需要哪些权限，还是全给
3 添加token的时候提示添加成功（给的是全部权限），但是下面显示500错误，这个应该怎么排错呢

**Comment by AnYeMoWang** [comment]
@lupus721 你好:
1. 之前的代码在配置这两个参数的地方存在问题，我们已经在 #10 中修复了这个问题并且更新了文档。你可以重新获取代码、build镜像后配置使用。
2. 最好给全部的权限、我们目前也没有测试过非全部权限下爬取是否会有问题。
3. 你这个500错误可以把network截图给我们看一下，我们目前无法复现这个问题。

**Comment by lupus721** [comment]
好的，git pull 然后重新运行，都ok了，没有500错误了，现在已经跑起来了。感谢
