### ISSUE TITLE
邮件发送不了

### ISSUE THREAD

**Issue by Guodafeng-tl** [VKSRC/Github-Monitor#90]
哪位大佬能帮忙解答一下邮件的发送和接收配置吗，万分感谢~~~~

**Comment by AnYeMoWang** [comment]
@Guodafeng-tl 按照README里修改 .env 文件里的邮箱配置即可
```
# Email Settings
# If you do not fill it in, it is None/False
EMAIL_HOST="smtp.example.com"  # smtp host
EMAIL_PORT="25"  # smtp port
FROM_EMAIL="secuirty@example.com"  # 发件人
EMAIL_HOST_USER="security@example.com"  # email user, 如为匿名发送，将值设为空字符即可
EMAIL_HOST_PASSWORD="password123!@#"  # email password, 如为匿名发送，将值设为空字符即可
EMAIL_USE_TLS="False"  # 与SMTP服务器通信时是否使用TLS（安全）连接, 可选True/False
EMAIL_USE_SSL="False"  # 与SMTP服务器通信时是否使用SSL（安全）连接, 可选True/False

```

**Comment by Guodafeng-tl** [comment]
谢谢你～



---原始邮件---
发件人: "暗夜膜王"<notifications@github.com&gt;
发送时间: 2020年9月8日(周二) 晚上6:08
收件人: "VKSRC/Github-Monitor"<Github-Monitor@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Guodafeng-tl"<2297743001@qq.com&gt;;
主题: Re: [VKSRC/Github-Monitor] 邮件发送不了 (#90)




 
@Guodafeng-tl 按照README里修改 .env 文件里的邮箱配置即可
 # Email Settings # If you do not fill it in, it is None/False EMAIL_HOST="smtp.example.com"  # smtp host EMAIL_PORT="25"  # smtp port FROM_EMAIL="secuirty@example.com"  # 发件人 EMAIL_HOST_USER="security@example.com"  # email user, 如为匿名发送，将值设为空字符即可 EMAIL_HOST_PASSWORD="password123!@#"  # email password, 如为匿名发送，将值设为空字符即可 EMAIL_USE_TLS="False"  # 与SMTP服务器通信时是否使用TLS（安全）连接, 可选True/False EMAIL_USE_SSL="False"  # 与SMTP服务器通信时是否使用SSL（安全）连接, 可选True/False
