### ISSUE TITLE
目前项目访问的github服务接口是什么？

### ISSUE THREAD

**Issue by yixuanzi** [VKSRC/Github-Monitor#92]
您好，我们近期使用了你们的项目来进行github泄露监控，因为我们生产网络的特殊性，互联网接口访问只能开通定向的ip访问策略并通过手动配置host的形式来进行访问。

我们在测试环境中成功部署系统并测试通过（互联网访问正常），单在生产环境中任务执行失败，没有结果，也没找到相关的日志输出。（生产环境的网络环境：手动配置有api.github.com github.com 域名，并能正常访问对应域名ip的443端口）

基于此，能够告知系统后台访问的github接口详细地址；是否存在相关的日志输出以便于自行排查问题，多谢！

**Comment by AnYeMoWang** [comment]
@yixuanzi 请求的github地址为 https://api.github.com/***

**Comment by yixuanzi** [comment]
感谢
